SET AUTOCOMMIT FALSE;

START TRANSACTION;

INSERT INTO SYS_M_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESC) VALUES
	('GUEST_ID', '0', 'SYS', 'SYS');
INSERT INTO SYS_M_ROLE_MAP_FUNCTION (ID_ROLE, ID_FUNCTION) VALUES
	('0', 'COM000000');	
INSERT INTO SYS_M_MENU (ID_MENU, NAME, LEVEL, MENU_TYPE, ID_PARENT, ID_ACTION, SEQ, ID_FUNCTION)VALUES
    (1001001, 'HOME', 0, 'T', NULL, 1001001, 0, 'COM000000');
INSERT INTO SYS_M_ACTION (ID_ACTION, PAGE_NAME, ACTION_NAME, NAME_SPACE, URL, TYPE, ID_MENU, ID_FUNCTION)
VALUES
	(1001001, 'HOME', 'home-end', '/home', NULL, 'A', NULL, 'COM000000');
INSERT INTO SYS_M_LABEL (LANGUAGE, PAGE, LABEL, DISPLAY_TEXT)
VALUES
	('ENG', 'MENU', 'HOME', 'HOME'),('THA', 'MENU', 'HOME', 'หน้าหลัก');


	
COMMIT;

SET AUTOCOMMIT TRUE;