
CREATE TABLE IF NOT EXISTS SYS_M_ACTION (
ID_ACTION BIGINT AUTO_INCREMENT PRIMARY KEY,
PAGE_NAME varchar(50) NOT NULL,
ACTION_NAME varchar(255) DEFAULT NULL,
NAME_SPACE varchar(50) DEFAULT NULL,
URL varchar(255) DEFAULT NULL,
TYPE char(1) NOT NULL,
ID_MENU BIGINT DEFAULT NULL,
ID_FUNCTION varchar(32) NOT NULL,
INPUT_RESULT_NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
 BIGINT AUTO_INCREMENT PRIMARY KEY
);

/*Table structure for table SYS_M_ADDRESS */



CREATE TABLE IF NOT EXISTS SYS_M_ADDRESS (
ID_ADDRESS BIGINT AUTO_INCREMENT PRIMARY KEY,
HOUSING_NO varchar(255) DEFAULT NULL,
STREET_ADDRESS1 varchar(255) DEFAULT NULL,
STREET_ADDRESS2 varchar(255) DEFAULT NULL,
ID_COUNTRY BIGINT DEFAULT NULL,
ID_PROVINCE BIGINT DEFAULT NULL,
ID_CITY BIGINT DEFAULT NULL,
ID_COUNTY BIGINT DEFAULT NULL,
ZIPCODE varchar(255) DEFAULT NULL,
LAT varchar(255) DEFAULT NULL,
LNG varchar(255) DEFAULT NULL,
DESCRIPTION text,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_ADDRESS_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_ADDRESS_LANG (
ID_ADDRESS_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_ADDRESS BIGINT NOT NULL,
LANG_CODE3 varchar(3) NOT NULL,
HOUSING_NO varchar(255) DEFAULT NULL,
STREET_ADDRESS1 varchar(255) DEFAULT NULL,
STREET_ADDRESS2 varchar(255) DEFAULT NULL,
ZIPCODE varchar(255) DEFAULT NULL,
DESCRIPTION text,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_ADDRESS_MAP_PHONE */



CREATE TABLE IF NOT EXISTS SYS_M_ADDRESS_MAP_PHONE (
ID_ADDRESS_MAP_PHONE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_ADDRESS BIGINT NOT NULL,
ID_PHONE BIGINT NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CITY */



CREATE TABLE IF NOT EXISTS SYS_M_CITY (
ID_COUNTRY BIGINT NOT NULL,
ID_PROVINCE BIGINT NOT NULL,
ID_CITY BIGINT AUTO_INCREMENT,
NAME varchar(255) DEFAULT NULL,
INDEX_ROW BIGINT DEFAULT NULL,
CODE varchar(255) DEFAULT NULL,
CODE2 varchar(2) DEFAULT NULL,
CODE3 varchar(3) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CITY_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_CITY_LANG (
ID_CITY_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_COUNTRY BIGINT DEFAULT NULL,
ID_PROVINCE BIGINT DEFAULT NULL,
ID_CITY BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CMS */



CREATE TABLE IF NOT EXISTS SYS_M_CMS (
LANG_CODE3 varchar(3) NOT NULL,
PAGE_NAME varchar(255) NOT NULL,
CONTENT text,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (LANG_CODE3,PAGE_NAME)
);

/*Table structure for table SYS_M_CONFIG */



CREATE TABLE IF NOT EXISTS SYS_M_CONFIG (
CONFIG_KEY varchar(100) NOT NULL PRIMARY KEY,
CONFIG_VALUE text NOT NULL,
CONFIG_GROUP varchar(100) NOT NULL,
DESC varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CONFIG_BY_CODE */



CREATE TABLE IF NOT EXISTS SYS_M_CONFIG_BY_CODE (
CONFIG_KEY varchar(100) NOT NULL,
CONFIG_CODE BIGINT NOT NULL,
CONFIG_VALUE varchar(255) NOT NULL,
CONFIG_GROUP varchar(100) NOT NULL,
DESC varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (CONFIG_KEY,CONFIG_CODE)
);

/*Table structure for table SYS_M_COUNTRY */



CREATE TABLE IF NOT EXISTS SYS_M_COUNTRY (
ID_COUNTRY BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME varchar(255) DEFAULT NULL,
CODE2 varchar(2) DEFAULT NULL,
CODE3 varchar(3) DEFAULT NULL,
ID_REGION BIGINT DEFAULT NULL,
ID_LANGUAGE BIGINT DEFAULT NULL,
ID_CURRENCY BIGINT DEFAULT NULL,
PHONE_CODE varchar(10) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_COUNTRY_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_COUNTRY_LANG (
ID_COUNTRY_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_COUNTRY BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_COUNTRY_MAP_PHONE_CODE */



CREATE TABLE IF NOT EXISTS SYS_M_COUNTRY_MAP_PHONE_CODE (
ID_COUNTRY_MAP_PHONE_CODE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_COUNTRY BIGINT DEFAULT NULL,
ID_PHONE_CODE BIGINT DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_COUNTY */



CREATE TABLE IF NOT EXISTS SYS_M_COUNTY (
ID_COUNTRY BIGINT NOT NULL,
ID_PROVINCE BIGINT NOT NULL,
ID_CITY BIGINT NOT NULL,
ID_COUNTY BIGINT AUTO_INCREMENT,
NAME varchar(255) DEFAULT NULL,
INDEX_ROW BIGINT DEFAULT NULL,
CODE varchar(255) DEFAULT NULL,
CODE2 varchar(2) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (ID_COUNTRY,ID_PROVINCE,ID_CITY,ID_COUNTY)
);

/*Table structure for table SYS_M_COUNTY_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_COUNTY_LANG (
ID_COUNTY_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_COUNTRY BIGINT DEFAULT NULL,
ID_PROVINCE BIGINT DEFAULT NULL,
ID_CITY BIGINT DEFAULT NULL,
ID_COUNTY BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CURRENCY */



CREATE TABLE IF NOT EXISTS SYS_M_CURRENCY (
ID_CURRENCY BIGINT AUTO_INCREMENT PRIMARY KEY,
SEQ smallint(6) DEFAULT NULL,
CODE3 char(3) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CURRENCY_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_CURRENCY_LANG (
ID_CURRENCY_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_CURRENCY BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) NOT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_CURRENCY_USD_RATE */



CREATE TABLE IF NOT EXISTS SYS_M_CURRENCY_USD_RATE (
ID_CURRENCY_USD_RATE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_CURRENCY BIGINT NOT NULL,
SEQ smallint(6) DEFAULT NULL,
CODE3 char(3) DEFAULT NULL,
RATE decimal(20,7) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_FIELD_HELP */



CREATE TABLE IF NOT EXISTS SYS_M_FIELD_HELP (
ID_FIELD_HELP BIGINT AUTO_INCREMENT PRIMARY KEY,
PAGE varchar(255) DEFAULT NULL,
FIELD varchar(255) DEFAULT NULL,
HELP_MESSAGE varchar(255) DEFAULT NULL,
HELP_MESSAGE_PARAMETER varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_FIELD_VALIDATOR */



CREATE TABLE IF NOT EXISTS SYS_M_FIELD_VALIDATOR (
ID_FIELD_VALIDATOR BIGINT AUTO_INCREMENT PRIMARY KEY,
CODE varchar(3) NOT NULL DEFAULT '---',
PAGE varchar(255) DEFAULT NULL,
FIELD varchar(255) DEFAULT NULL,
PRE_CON BIGINT DEFAULT NULL,
SEQ int(11) DEFAULT NULL,
TYPE varchar(255) DEFAULT NULL,
PARAMETER varchar(1024) DEFAULT NULL,
MESSAGE_KEY varchar(255) DEFAULT NULL,
MESSAGE varchar(255) DEFAULT NULL,
MESSAGE_PARAMETER varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_FUNCTION */



CREATE TABLE IF NOT EXISTS SYS_M_FUNCTION (
ID_FUNCTION varchar(32) NOT NULL PRIMARY KEY,
NAME varchar(255) NOT NULL,
LEVEL smallint(11) NOT NULL,
ID_PARENT varchar(32) DEFAULT NULL,
DESC varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_GEN_KEY */



CREATE TABLE IF NOT EXISTS SYS_M_GEN_KEY (
ID_GEN_KEY BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_ID BIGINT NOT NULL,
KEY_GEN varchar(255) NOT NULL,
KEY_TYPE varchar(2) NOT NULL,
JSON_DATA text,
TIME_OUT timestamp NULL DEFAULT NULL,
USED char(1) DEFAULT 'N',
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_LABEL */



CREATE TABLE IF NOT EXISTS SYS_M_LABEL (
LANGUAGE varchar(50) NOT NULL,
PAGE varchar(50) NOT NULL,
LABEL varchar(50) NOT NULL,
DISPLAY_TEXT text NOT NULL,
DESC text,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (LANGUAGE,PAGE,LABEL)
);

/*Table structure for table SYS_M_MENU */



CREATE TABLE IF NOT EXISTS SYS_M_MENU (
ID_MENU BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME varchar(50) NOT NULL,
LEVEL smallint(11) NOT NULL,
MENU_TYPE varchar(1) DEFAULT NULL COMMENT 'T=TOP, S=SUB MENU, N=NAVIGATE, R=ROOT',
ID_PARENT BIGINT DEFAULT NULL,
ID_ACTION BIGINT DEFAULT NULL,
SEQ int(11) DEFAULT NULL,
ID_FUNCTION varchar(32) NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_MESSAGE */



CREATE TABLE IF NOT EXISTS SYS_M_MESSAGE (
MESSAGE_CODE varchar(50) NOT NULL,
MESSAGE_LANG varchar(10) NOT NULL,
DISPLAY_TEXT varchar(255) NOT NULL,
MESSAGE_DESC varchar(255) DEFAULT NULL,
MESSAGE_TYPE varchar(10) NOT NULL,
SOLUTION varchar(255) DEFAULT NULL,
REMARK varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (MESSAGE_CODE,MESSAGE_LANG)
);

/*Table structure for table SYS_M_PERMISSION_GROUP */



CREATE TABLE IF NOT EXISTS SYS_M_PERMISSION_GROUP (
ID_PERMISSION_GROUP BIGINT NOT NULL,
MODULE varchar(255) NOT NULL,
NAME varchar(255) NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PERMISSION_GROUP_MAP_FUNCTION */



CREATE TABLE IF NOT EXISTS SYS_M_PERMISSION_GROUP_MAP_FUNCTION (
ID_PERMISSION_GROUP_MAP_FUNCTION BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_PERMISSION_GROUP BIGINT NOT NULL,
ID_FUNCTION varchar(32) NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PERMISSION_GROUP_MAP_USER */



CREATE TABLE IF NOT EXISTS SYS_M_PERMISSION_GROUP_MAP_USER (
ID_PERMISSION_GROUP_MAP_USER BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_PERMISSION_GROUP BIGINT NOT NULL,
ID_USER BIGINT NOT NULL,
KEY_FUNCTION varchar(32) NOT NULL,
ID_GEN_KEY BIGINT DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PERMISSION_TRANSLATE */



CREATE TABLE IF NOT EXISTS SYS_M_PERMISSION_TRANSLATE (
ID_PERMISSION_TRANSLATE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT DEFAULT NULL,
ID_LANGUAGE BIGINT DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PHONE */



CREATE TABLE IF NOT EXISTS SYS_M_PHONE (
ID_PHONE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_PHONE_TYPE BIGINT DEFAULT NULL,
PHONE_PREFIX varchar(255) DEFAULT NULL,
ID_PHONE_CODE BIGINT DEFAULT NULL,
PHONE_NO varchar(255) DEFAULT NULL,
PHONE_EXT varchar(255) DEFAULT NULL,
TIME_START time DEFAULT NULL,
TIME_END time DEFAULT NULL,
TIME_DURATION_MINUTE int(11) DEFAULT NULL,
SEQ smallint(6) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PHONE_CODE */



CREATE TABLE IF NOT EXISTS SYS_M_PHONE_CODE (
ID_PHONE_CODE BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME varchar(10) DEFAULT NULL,
REF_COUNTRY varchar(255) DEFAULT NULL,
REF_COUNTRY_CODE varchar(2) DEFAULT NULL,
REF_INDEX int(11) DEFAULT NULL,
REF_C varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PHONE_TYPE */



CREATE TABLE IF NOT EXISTS SYS_M_PHONE_TYPE (
ID_PHONE_TYPE BIGINT AUTO_INCREMENT PRIMARY KEY,
SEQ smallint(6) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PHONE_TYPE_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_PHONE_TYPE_LANG (
ID_PHONE_TYPE_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_PHONE_TYPE BIGINT NOT NULL,
LANG_CODE3 varchar(3) DEFAULT NULL,
SEQ smallint(6) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PREFIX_NAME */



CREATE TABLE IF NOT EXISTS SYS_M_PREFIX_NAME (
ID_PREFIX_NAME BIGINT AUTO_INCREMENT PRIMARY KEY,
SEQ smallint(6) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PREFIX_NAME_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_PREFIX_NAME_LANG (
ID_PREFIX_NAME_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_PREFIX_NAME BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) NOT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_PROVINCE */



CREATE TABLE IF NOT EXISTS SYS_M_PROVINCE (
ID_COUNTRY BIGINT NOT NULL,
ID_PROVINCE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_ZONE BIGINT DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
CODE2 varchar(2) DEFAULT NULL,
CODE3 varchar(3) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (ID_PROVINCE,ID_COUNTRY)
);

/*Table structure for table SYS_M_PROVINCE_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_PROVINCE_LANG (
ID_PROVINCE_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_COUNTRY BIGINT DEFAULT NULL,
ID_PROVINCE BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_ROLE */



CREATE TABLE IF NOT EXISTS SYS_M_ROLE (
ID_ROLE BIGINT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME varchar(64) NOT NULL,
DESC varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_ROLE_MAP_FUNCTION */



CREATE TABLE IF NOT EXISTS SYS_M_ROLE_MAP_FUNCTION (
ID_ROLE BIGINT NOT NULL,
ID_FUNCTION varchar(32) NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (ID_ROLE,ID_FUNCTION)
);

/*Table structure for table SYS_M_SOCIAL_NETWORK */



CREATE TABLE IF NOT EXISTS SYS_M_SOCIAL_NETWORK (
ID_SOCIAL_NETWORK BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT DEFAULT NULL,
ID_SOCIAL_NETWORK_TYPE BIGINT DEFAULT NULL,
SOCIAL_PROFILE_ID varchar(255) DEFAULT NULL,
SOCIAL_OAUTH_TOKEN varchar(255) DEFAULT NULL,
SOCIAL_OAUTH_SECRET_TOKEN varchar(400) DEFAULT NULL,
SOCIAL_ACCOUNT_NAME varchar(255) DEFAULT NULL,
EMAIL_SOCIAL_ACCOUNT varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_SOCIAL_NETWORK_TYPE */



CREATE TABLE IF NOT EXISTS SYS_M_SOCIAL_NETWORK_TYPE (
ID_SOCIAL_NETWORK_TYPE BIGINT AUTO_INCREMENT PRIMARY KEY,
SEQ smallint(6) DEFAULT NULL,
NAME varchar(255) DEFAULT NULL,
IMAGE_LOGO_PATH varchar(255) DEFAULT NULL,
TIP varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_SOCIAL_NETWORK_TYPE_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_SOCIAL_NETWORK_TYPE_LANG (
ID_SOCIAL_NETWORK_TYPE_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_SOCIAL_NETWORK_TYPE BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) NOT NULL,
NAME varchar(255) DEFAULT NULL,
TIP varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_USER */



CREATE TABLE IF NOT EXISTS SYS_M_USER (
ID_USER BIGINT AUTO_INCREMENT PRIMARY KEY,
USERNAME varchar(255) NOT NULL,
PASSWORD varchar(32) DEFAULT NULL,
ID_PREFIX_NAME BIGINT DEFAULT NULL,
FIRST_NAME varchar(255) DEFAULT NULL,
MID_NAME varchar(255) DEFAULT NULL,
LAST_NAME varchar(255) DEFAULT NULL,
MAIDEN_SURNAME varchar(255) DEFAULT NULL,
NICK_NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_USER_CRITERIA */



CREATE TABLE IF NOT EXISTS SYS_M_USER_CRITERIA (
ID_USER_CRITERIA BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT DEFAULT NULL,
KEY_ID BIGINT DEFAULT NULL
);

/*Table structure for table SYS_M_USER_DEFAULT */



CREATE TABLE IF NOT EXISTS SYS_M_USER_DEFAULT (
ID_USER BIGINT NOT NULL PRIMARY KEY,
MODULE varchar(255) NOT NULL,
KEY_FUNCTION varchar(32) NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_USER_LANG */



CREATE TABLE IF NOT EXISTS SYS_M_USER_LANG (
ID_USER_LANG BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT DEFAULT NULL,
LANG_CODE3 varchar(3) NOT NULL,
ID_PREFIX_NAME BIGINT DEFAULT NULL,
FIRST_NAME varchar(255) DEFAULT NULL,
MID_NAME varchar(255) DEFAULT NULL,
LAST_NAME varchar(255) DEFAULT NULL,
MAIDEN_SURNAME varchar(255) DEFAULT NULL,
NICK_NAME varchar(255) DEFAULT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_USER_MAP_ADDRESS */



CREATE TABLE IF NOT EXISTS SYS_M_USER_MAP_ADDRESS (
ID_USER_MAP_ADDRESS BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT NOT NULL,
ID_ADDRESS BIGINT NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_USER_MAP_PHONE */



CREATE TABLE IF NOT EXISTS SYS_M_USER_MAP_PHONE (
ID_USER_MAP_PHONE BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT NOT NULL,
ID_PHONE BIGINT NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

/*Table structure for table SYS_M_USER_MAP_ROLE */



CREATE TABLE IF NOT EXISTS SYS_M_USER_MAP_ROLE (
ID_USER BIGINT NOT NULL,
ID_ROLE BIGINT NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL,
PRIMARY KEY (ID_USER,ID_ROLE)
);

/*Table structure for table SYS_M_USER_MAP_SOCIAL_NETWORK */

CREATE TABLE IF NOT EXISTS SYS_M_USER_MAP_SOCIAL_NETWORK (
ID_USER_MAP_SOCIAL_NETWORK BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USER BIGINT NOT NULL,
ID_SOCIAL_NETWORK BIGINT NOT NULL,
STATUS char(1) DEFAULT 'A',
CREATE_DATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
CREATE_USER varchar(255) DEFAULT NULL,
UPDATE_DATE timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
UPDATE_USER varchar(255) DEFAULT NULL
);

