package com.moomanow.web.common.bean;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="SYS_M_CITY"
)
public class City  implements java.io.Serializable,com.moomanow.core.common.bean.EntityBean {


     private CityId id;
     private Province province;
     private String name;
     private Long indexRow;
     private String code;
     private String code2;
     private String code3;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<County> counties = new ArrayList<County>(0);

    public City() {
    }

	
    public City(CityId id, Province province) {
        this.id = id;
        this.province = province;
    }
    public City(CityId id, Province province, String name, Long indexRow, String code, String code2, String code3, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<County> counties) {
       this.id = id;
       this.province = province;
       this.name = name;
       this.indexRow = indexRow;
       this.code = code;
       this.code2 = code2;
       this.code3 = code3;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.counties = counties;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCountry", column=@Column(name="ID_COUNTRY", nullable=false) ), 
        @AttributeOverride(name="idProvince", column=@Column(name="ID_PROVINCE", nullable=false) ), 
        @AttributeOverride(name="idCity", column=@Column(name="ID_CITY", nullable=false) ) } )
    public CityId getId() {
        return this.id;
    }
    
    public void setId(CityId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_COUNTRY", referencedColumnName="ID_COUNTRY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ID_PROVINCE", referencedColumnName="ID_PROVINCE", nullable=false, insertable=false, updatable=false) } )
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="INDEX_ROW")
    public Long getIndexRow() {
        return this.indexRow;
    }
    
    public void setIndexRow(Long indexRow) {
        this.indexRow = indexRow;
    }

    
    @Column(name="CODE")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="CODE2", length=2)
    public String getCode2() {
        return this.code2;
    }
    
    public void setCode2(String code2) {
        this.code2 = code2;
    }

    
    @Column(name="CODE3", length=3)
    public String getCode3() {
        return this.code3;
    }
    
    public void setCode3(String code3) {
        this.code3 = code3;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public List<County> getCounties() {
        return this.counties;
    }
    
    public void setCounties(List<County> counties) {
        this.counties = counties;
    }




}


