package com.moomanow.web.common.bean;



import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountryMapPhoneCode generated by hbm2java
 */
@Entity
@Table(name="SYS_M_COUNTRY_MAP_PHONE_CODE"
)
public class CountryMapPhoneCode  implements java.io.Serializable,com.moomanow.core.common.bean.EntityBean {


     private Long idCountryMapPhoneCode;
     private Country country;
     private PhoneCode phoneCode;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public CountryMapPhoneCode() {
    }

	
    public CountryMapPhoneCode(Date createDate) {
        this.createDate = createDate;
    }
    public CountryMapPhoneCode(Country country, PhoneCode phoneCode, String status, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.country = country;
       this.phoneCode = phoneCode;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_COUNTRY_MAP_PHONE_CODE", unique=true, nullable=false)
    public Long getIdCountryMapPhoneCode() {
        return this.idCountryMapPhoneCode;
    }
    
    public void setIdCountryMapPhoneCode(Long idCountryMapPhoneCode) {
        this.idCountryMapPhoneCode = idCountryMapPhoneCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COUNTRY")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PHONE_CODE")
    public PhoneCode getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(PhoneCode phoneCode) {
        this.phoneCode = phoneCode;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


