package com.moomanow.web.common.bean;

// Generated Sep 15, 2014 1:37:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysMGenKey generated by hbm2java
 */
@Entity
@Table(name = "SYS_M_GEN_KEY")
public class GenKey implements java.io.Serializable,
com.moomanow.core.common.bean.EntityBean {

	private Long idGenKey;
	private long userId;
	private String keyGen;
	private String keyType;
	private Date timeOut;
	private String status;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;

	public GenKey() {
	}

	public GenKey(long userId, String keyGen, String keyType) {
		this.userId = userId;
		this.keyGen = keyGen;
		this.keyType = keyType;
	}

	public GenKey(long userId, String keyGen, String keyType, Date timeOut,
			String status, Date createDate, String createUser, Date updateDate,
			String updateUser) {
		this.userId = userId;
		this.keyGen = keyGen;
		this.keyType = keyType;
		this.timeOut = timeOut;
		this.status = status;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_GEN_KEY", unique = true, nullable = false)
	public Long getIdGenKey() {
		return this.idGenKey;
	}

	public void setIdGenKey(Long idGenKey) {
		this.idGenKey = idGenKey;
	}

	@Column(name = "USER_ID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "KEY_GEN", nullable = false)
	public String getKeyGen() {
		return this.keyGen;
	}

	public void setKeyGen(String keyGen) {
		this.keyGen = keyGen;
	}

	@Column(name = "KEY_TYPE", nullable = false, length = 2)
	public String getKeyType() {
		return this.keyType;
	}

	public void setKeyType(String keyType) {
		this.keyType = keyType;
	}

	@Column(name = "TIME_OUT")
    @Temporal(TemporalType.TIMESTAMP)
	public Date getTimeOut() {
		return this.timeOut;
	}

	public void setTimeOut(Date timeOut) {
		this.timeOut = timeOut;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER")
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_USER")
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
