package com.moomanow.web.common.bean;



import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhoneCode generated by hbm2java
 */
@Entity
@Table(name="SYS_M_PHONE_CODE"
)
public class PhoneCode  implements java.io.Serializable,com.moomanow.core.common.bean.EntityBean {


     private Long idPhoneCode;
     private String phoneCode;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<CountryMapPhoneCode> countryMapPhoneCodes = new ArrayList<CountryMapPhoneCode>(0);
     private List<Phone> phones = new ArrayList<Phone>(0);

    public PhoneCode() {
    }

	
    public PhoneCode(Date createDate) {
        this.createDate = createDate;
    }
    public PhoneCode(String phoneCode, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<CountryMapPhoneCode> countryMapPhoneCodes, List<Phone> phones) {
       this.phoneCode = phoneCode;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.countryMapPhoneCodes = countryMapPhoneCodes;
       this.phones = phones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PHONE_CODE", unique=true, nullable=false)
    public Long getIdPhoneCode() {
        return this.idPhoneCode;
    }
    
    public void setIdPhoneCode(Long idPhoneCode) {
        this.idPhoneCode = idPhoneCode;
    }

    
    @Column(name="PHONE_CODE", length=10)
    public String getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phoneCode")
    public List<CountryMapPhoneCode> getCountryMapPhoneCodes() {
        return this.countryMapPhoneCodes;
    }
    
    public void setCountryMapPhoneCodes(List<CountryMapPhoneCode> countryMapPhoneCodes) {
        this.countryMapPhoneCodes = countryMapPhoneCodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phoneCode")
    public List<Phone> getPhones() {
        return this.phones;
    }
    
    public void setPhones(List<Phone> phones) {
        this.phones = phones;
    }



}


