package com.moomanow.web.common.bean;
// Generated Nov 1, 2016 2:55:18 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name="SYS_M_PHONE"
)
public class Phone  implements java.io.Serializable {


     private Long idPhone;
     private PhoneCode phoneCode;
     private PhoneType phoneType;
     private String phonePrefix;
     private String phoneNo;
     private String phoneExt;
     private Date timeStart;
     private Date timeEnd;
     private Integer timeDurationMinute;
     private Integer seq;
     private String name;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public Phone() {
    }

    public Phone(PhoneCode phoneCode, PhoneType phoneType, String phonePrefix, String phoneNo, String phoneExt, Date timeStart, Date timeEnd, Integer timeDurationMinute, Integer seq, String name, String status, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.phoneCode = phoneCode;
       this.phoneType = phoneType;
       this.phonePrefix = phonePrefix;
       this.phoneNo = phoneNo;
       this.phoneExt = phoneExt;
       this.timeStart = timeStart;
       this.timeEnd = timeEnd;
       this.timeDurationMinute = timeDurationMinute;
       this.seq = seq;
       this.name = name;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PHONE", unique=true, nullable=false)
    public Long getIdPhone() {
        return this.idPhone;
    }
    
    public void setIdPhone(Long idPhone) {
        this.idPhone = idPhone;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PHONE_CODE")
    public PhoneCode getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(PhoneCode phoneCode) {
        this.phoneCode = phoneCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PHONE_TYPE")
    public PhoneType getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(PhoneType phoneType) {
        this.phoneType = phoneType;
    }

    
    @Column(name="PHONE_PREFIX")
    public String getPhonePrefix() {
        return this.phonePrefix;
    }
    
    public void setPhonePrefix(String phonePrefix) {
        this.phonePrefix = phonePrefix;
    }

    
    @Column(name="PHONE_NO")
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="PHONE_EXT")
    public String getPhoneExt() {
        return this.phoneExt;
    }
    
    public void setPhoneExt(String phoneExt) {
        this.phoneExt = phoneExt;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="TIME_START", length=8)
    public Date getTimeStart() {
        return this.timeStart;
    }
    
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="TIME_END", length=8)
    public Date getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    
    @Column(name="TIME_DURATION_MINUTE")
    public Integer getTimeDurationMinute() {
        return this.timeDurationMinute;
    }
    
    public void setTimeDurationMinute(Integer timeDurationMinute) {
        this.timeDurationMinute = timeDurationMinute;
    }

    
    @Column(name="SEQ")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

}


