package com.moomanow.web.common.bean;
// Generated Nov 1, 2016 2:55:18 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhoneCode generated by hbm2java
 */
@Entity
@Table(name="SYS_M_PHONE_CODE"
)
public class PhoneCode  implements java.io.Serializable {


     private Long idPhoneCode;
     private String name;
     private String refCountry;
     private String refCountryCode;
     private Integer refIndex;
     private String refC;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private Set<Phone> phones = new HashSet<Phone>(0);

    public PhoneCode() {
    }

	
    public PhoneCode(Date createDate) {
        this.createDate = createDate;
    }
    public PhoneCode(String name, String refCountry, String refCountryCode, Integer refIndex, String refC, String status, Date createDate, String createUser, Date updateDate, String updateUser, Set<Phone> phones) {
       this.name = name;
       this.refCountry = refCountry;
       this.refCountryCode = refCountryCode;
       this.refIndex = refIndex;
       this.refC = refC;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.phones = phones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PHONE_CODE", unique=true, nullable=false)
    public Long getIdPhoneCode() {
        return this.idPhoneCode;
    }
    
    public void setIdPhoneCode(Long idPhoneCode) {
        this.idPhoneCode = idPhoneCode;
    }

    
    @Column(name="NAME", length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="REF_COUNTRY")
    public String getRefCountry() {
        return this.refCountry;
    }
    
    public void setRefCountry(String refCountry) {
        this.refCountry = refCountry;
    }

    
    @Column(name="REF_COUNTRY_CODE", length=2)
    public String getRefCountryCode() {
        return this.refCountryCode;
    }
    
    public void setRefCountryCode(String refCountryCode) {
        this.refCountryCode = refCountryCode;
    }

    
    @Column(name="REF_INDEX")
    public Integer getRefIndex() {
        return this.refIndex;
    }
    
    public void setRefIndex(Integer refIndex) {
        this.refIndex = refIndex;
    }

    
    @Column(name="REF_C")
    public String getRefC() {
        return this.refC;
    }
    
    public void setRefC(String refC) {
        this.refC = refC;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phoneCode")
    public Set<Phone> getPhones() {
        return this.phones;
    }
    
    public void setPhones(Set<Phone> phones) {
        this.phones = phones;
    }




}


