package com.moomanow.web.common.bean;



import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name="SYS_M_PROVINCE"
)
public class Province  implements java.io.Serializable,com.moomanow.core.common.bean.EntityBean {


     private ProvinceId id;
     private Country country;
     private String name;
     private String code2;
     private String code3;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<City> cities = new ArrayList<City>(0);

    public Province() {
    }

	
    public Province(ProvinceId id, Country country) {
        this.id = id;
        this.country = country;
    }
    public Province(ProvinceId id, Country country, String name, String code2, String code3, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<City> cities) {
       this.id = id;
       this.country = country;
       this.name = name;
       this.code2 = code2;
       this.code3 = code3;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.cities = cities;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCountry", column=@Column(name="ID_COUNTRY", nullable=false) ), 
        @AttributeOverride(name="idProvince", column=@Column(name="ID_PROVINCE", nullable=false) ) } )
    public ProvinceId getId() {
        return this.id;
    }
    
    public void setId(ProvinceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COUNTRY", nullable=false, insertable=false, updatable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="CODE2", length=2)
    public String getCode2() {
        return this.code2;
    }
    
    public void setCode2(String code2) {
        this.code2 = code2;
    }

    
    @Column(name="CODE3", length=3)
    public String getCode3() {
        return this.code3;
    }
    
    public void setCode3(String code3) {
        this.code3 = code3;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="province")
    public List<City> getCities() {
        return this.cities;
    }
    
    public void setCities(List<City> cities) {
        this.cities = cities;
    }




}


