package com.moomanow.web.common.bean;

// Generated Sep 15, 2014 1:37:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysMRoleMapFunction generated by hbm2java
 */
@Entity
@Table(name = "SYS_M_ROLE_MAP_FUNCTION")
public class RoleMapFunction implements java.io.Serializable,
com.moomanow.core.common.bean.EntityBean {

	private RoleMapFunctionId id;
	private String status;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;

	public RoleMapFunction() {
	}

	public RoleMapFunction(RoleMapFunctionId id) {
		this.id = id;
	}

	public RoleMapFunction(RoleMapFunctionId id, String status,
			Date createDate, String createUser, Date updateDate,
			String updateUser) {
		this.id = id;
		this.status = status;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idRole", column = @Column(name = "ID_ROLE", nullable = false)),
			@AttributeOverride(name = "idFunction", column = @Column(name = "ID_FUNCTION", nullable = false, length = 32)) })
	public RoleMapFunctionId getId() {
		return this.id;
	}

	public void setId(RoleMapFunctionId id) {
		this.id = id;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER")
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_USER")
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
