package com.moomanow.web.common.bean;

// Generated Sep 15, 2014 1:37:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysMRoleMapFunctionId generated by hbm2java
 */
@Embeddable
public class RoleMapFunctionId implements java.io.Serializable {

	private long idRole;
	private String idFunction;

	public RoleMapFunctionId() {
	}

	public RoleMapFunctionId(long idRole, String idFunction) {
		this.idRole = idRole;
		this.idFunction = idFunction;
	}

	@Column(name = "ID_ROLE", nullable = false)
	public long getIdRole() {
		return this.idRole;
	}

	public void setIdRole(long idRole) {
		this.idRole = idRole;
	}

	@Column(name = "ID_FUNCTION", nullable = false, length = 32)
	public String getIdFunction() {
		return this.idFunction;
	}

	public void setIdFunction(String idFunction) {
		this.idFunction = idFunction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleMapFunctionId))
			return false;
		RoleMapFunctionId castOther = (RoleMapFunctionId) other;

		return (this.getIdRole() == castOther.getIdRole())
				&& ((this.getIdFunction() == castOther.getIdFunction()) || (this
						.getIdFunction() != null
						&& castOther.getIdFunction() != null && this
						.getIdFunction().equals(castOther.getIdFunction())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdRole();
		result = 37
				* result
				+ (getIdFunction() == null ? 0 : this.getIdFunction()
						.hashCode());
		return result;
	}

}
