package com.moomanow.web.common.bean;



import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SocialNetworkType generated by hbm2java
 */
@Entity
@Table(name="SYS_M_SOCIAL_NETWORK_TYPE"
)
public class SocialNetworkType  implements java.io.Serializable,com.moomanow.core.common.bean.EntityBean {


     private Long idSocialNetworkType;
     private Integer seq;
     private String name;
     private String imageLogoPath;
     private String tip;
     private String status;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private List<SocialNetwork> socialNetworks = new ArrayList<SocialNetwork>(0);

    public SocialNetworkType() {
    }

    public SocialNetworkType(Integer seq, String name, String imageLogoPath, String tip, String status, Date createDate, String createUser, Date updateDate, String updateUser, List<SocialNetwork> socialNetworks) {
       this.seq = seq;
       this.name = name;
       this.imageLogoPath = imageLogoPath;
       this.tip = tip;
       this.status = status;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.socialNetworks = socialNetworks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_SOCIAL_NETWORK_TYPE", unique=true, nullable=false)
    public Long getIdSocialNetworkType() {
        return this.idSocialNetworkType;
    }
    
    public void setIdSocialNetworkType(Long idSocialNetworkType) {
        this.idSocialNetworkType = idSocialNetworkType;
    }

    
    @Column(name="SEQ")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="IMAGE_LOGO_PATH")
    public String getImageLogoPath() {
        return this.imageLogoPath;
    }
    
    public void setImageLogoPath(String imageLogoPath) {
        this.imageLogoPath = imageLogoPath;
    }

    
    @Column(name="TIP")
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CREATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER")
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="UPDATE_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER")
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="socialNetworkType")
    public List<SocialNetwork> getSocialNetworks() {
        return this.socialNetworks;
    }
    
    public void setSocialNetworks(List<SocialNetwork> socialNetworks) {
        this.socialNetworks = socialNetworks;
    }

}


